chore: added catalogId and displayPath support
MapColonies/mc-models pull request #148
Opened 2022-09-18 08:22 UTC by CL-SHLOMIKONCHA

2022-09-18 08:27 UTC, cl-shaharshavit-rnd approved these changes

2022-09-18 11:31 UTC, cl-shaharshavit-rnd requested changes

2022-09-18 11:31 UTC, cl-shaharshavit-rnd commented on src/yaml/rasterCatalog/insertRequest.yaml
> +            id:
remove this as the id is already part of the metadata

2022-09-18 11:31 UTC, cl-shaharshavit-rnd commented on src/yaml/rasterCatalog/updateRequest.yaml
> +
is it still nessary?

2022-09-18 12:23 UTC, asafMasa requested changes

2022-09-18 12:23 UTC, asafMasa commented on src/models/rasterCatalog/rasterCatalogUpsertRequest.ts
> +  id: string;
same as @cl-shaharshavit-rnd remark, isn't it already exists in metadata?

2022-09-19 10:42 UTC, cl-shaharshavit-rnd requested changes

2022-09-19 10:42 UTC, cl-shaharshavit-rnd commented on src/models/pycsw/interfaces/pycswCoreModel.ts
> -  id: string | undefined;
revert

2022-09-19 10:42 UTC, cl-shaharshavit-rnd commented on src/models/layerMetadata/layerMetadata.ts
> +  id: string | undefined;
ask client team

2022-09-20 08:23 UTC, cl-shaharshavit-rnd approved these changes

2022-09-20 10:28 UTC, asafMasa requested changes

2022-09-20 10:28 UTC, asafMasa commented on src/models/layerMetadata/layerMetadata.ts
> +    isAutoGenerated: true,
it's not auto generated

Ask @alebinson if some property should be added so it won't be displayed

2022-09-20 11:11 UTC, asafMasa approved these changes

2022-09-20 14:38 UTC, alebinson approved these changes
In general PR is Ok.
There is an issue with allowed for editing fields the number of those fields is very limited (only 5 fields must be editable due to mc-models.xls)

I will open a relevant issue for raster team

2022-09-20 15:59 UTC, merged