feat!: adding format column (image content type)
MapColonies/mc-models pull request #169
Opened 2023-09-26 15:20 UTC by ronenkapelian

Adding new Catalog entity of Format -> associated with the image content type.

2023-09-27 13:32 UTC, asafMasa requested changes
👍

2023-09-27 13:32 UTC, asafMasa commented on package.json
> +    "@map-colonies/types": "^1.3.0"
">=1.3.0"

2023-09-28 05:46 UTC, alebinson approved these changes
looks good

2023-10-01 13:13 UTC, ronenkapelian commented on package.json
> +    "@map-colonies/types": "^1.3.0"
done

2023-10-01 13:13 UTC, merged