feat: polygon parts entity
MapColonies/mc-models pull request #183
Opened 2024-03-14 13:29 UTC by alebinson

2024-04-02 07:05 UTC, asafMasa requested changes

2024-04-21 06:45 UTC, alebinson commented on src/models/polygonParts/polygonPart.ts
> +  classification: string | undefined;
will be in Almog's PR (current data structure according to initial Shazir's EXCEL)

2024-04-21 06:45 UTC, alebinson commented on src/models/polygonParts/polygonPart.ts
> +  resolutionMeter: number | undefined;
will be in Almog's PR (current data structure according to initial Shazir's EXCEL)

2024-04-21 09:32 UTC, almog8k approved these changes

2024-04-21 09:46 UTC, EllaMartirosyan approved these changes

2024-04-21 10:01 UTC, netanelC approved these changes
Not related to 3D Team

2024-04-21 10:06 UTC, merged