fix: new raster ingestion modifications
MapColonies/mc-models pull request #189
Opened 2024-06-19 07:11 UTC by RonitKissis

2024-06-19 10:47 UTC, asafMasa requested changes

2024-06-19 10:47 UTC, asafMasa commented on src/yaml/ingestionTrigger/rasterLayerExample.yaml
> +          productId: c5e3f820-b2bd-4f0b-a70f-c98bf33b2692
revert

2024-06-19 10:47 UTC, asafMasa commented on src/yaml/ingestionTrigger/rasterLayerExample.yaml
> +          - id: c5e3f820-b2bd-4f0b-a70f-c98bf33b2692
revert

2024-06-19 11:57 UTC, asafMasa approved these changes

2024-06-19 12:54 UTC, netanelC approved these changes
Not related to 3D

2024-06-20 06:03 UTC, alebinson approved these changes
Basically looks good. That mean ONE thing: INTEGRATION will be LONGER

2024-06-20 14:07 UTC, merged